-- Seed test data for plotting functionality
-- This script creates dummy plants, sensors, and readings for testing the interactive plots

-- Insert test plants
INSERT INTO plants (name, species, description, location, min_soil_moisture, max_soil_moisture, watering_frequency, status, user_id, created_at, updated_at)
VALUES
    ('Tomato Plant', 'Solanum lycopersicum', 'Test tomato plant for plot testing', 'Garden Bed 1', 30, 70, 24, 'active', 1, NOW(), NOW()),
    ('Basil Plant', 'Ocimum basilicum', 'Test basil plant for plot testing', 'Garden Bed 2', 40, 80, 48, 'active', 1, NOW(), NOW()),
    ('Lettuce Plant', 'Lactuca sativa', 'Test lettuce plant for plot testing', 'Garden Bed 3', 35, 75, 36, 'active', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE updated_at = NOW();

-- Get plant IDs
SET @tomato_id = (SELECT id FROM plants WHERE name = 'Tomato Plant' LIMIT 1);
SET @basil_id = (SELECT id FROM plants WHERE name = 'Basil Plant' LIMIT 1);
SET @lettuce_id = (SELECT id FROM plants WHERE name = 'Lettuce Plant' LIMIT 1);

-- Insert test sensors
INSERT INTO sensors (name, type, location, description, plot_type, unit, status, user_id, created_at, updated_at)
VALUES
    ('Tomato Moisture Sensor', 'moisture', 'Garden Bed 1', 'Moisture sensor for tomato plant', 'moisture', '%', 'active', 1, NOW(), NOW()),
    ('Tomato Temperature Sensor', 'temperature', 'Garden Bed 1', 'Temperature sensor for tomato plant', 'temperature', '°C', 'active', 1, NOW(), NOW()),
    ('Basil Moisture Sensor', 'moisture', 'Garden Bed 2', 'Moisture sensor for basil plant', 'moisture', '%', 'active', 1, NOW(), NOW()),
    ('Basil Humidity Sensor', 'humidity', 'Garden Bed 2', 'Humidity sensor for basil plant', 'humidity', '%', 'active', 1, NOW(), NOW()),
    ('Lettuce Moisture Sensor', 'moisture', 'Garden Bed 3', 'Moisture sensor for lettuce plant', 'moisture', '%', 'active', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE updated_at = NOW();

-- Get sensor IDs
SET @tomato_moisture_id = (SELECT id FROM sensors WHERE name = 'Tomato Moisture Sensor' LIMIT 1);
SET @tomato_temp_id = (SELECT id FROM sensors WHERE name = 'Tomato Temperature Sensor' LIMIT 1);
SET @basil_moisture_id = (SELECT id FROM sensors WHERE name = 'Basil Moisture Sensor' LIMIT 1);
SET @basil_humidity_id = (SELECT id FROM sensors WHERE name = 'Basil Humidity Sensor' LIMIT 1);
SET @lettuce_moisture_id = (SELECT id FROM sensors WHERE name = 'Lettuce Moisture Sensor' LIMIT 1);

-- Link sensors to plants
INSERT INTO plant_sensors (plant_id, sensor_id, water_amount, last_watered, next_watering, created_at, updated_at)
VALUES
    (@tomato_id, @tomato_moisture_id, 100, NULL, DATE_ADD(NOW(), INTERVAL 24 HOUR), NOW(), NOW()),
    (@tomato_id, @tomato_temp_id, 100, NULL, DATE_ADD(NOW(), INTERVAL 24 HOUR), NOW(), NOW()),
    (@basil_id, @basil_moisture_id, 100, NULL, DATE_ADD(NOW(), INTERVAL 48 HOUR), NOW(), NOW()),
    (@basil_id, @basil_humidity_id, 100, NULL, DATE_ADD(NOW(), INTERVAL 48 HOUR), NOW(), NOW()),
    (@lettuce_id, @lettuce_moisture_id, 100, NULL, DATE_ADD(NOW(), INTERVAL 36 HOUR), NOW(), NOW())
ON DUPLICATE KEY UPDATE updated_at = NOW();

-- Insert readings for the last 7 days (multiple readings per day)
-- Generate readings every 2 hours for the last 7 days
-- This creates 84 readings per sensor (7 days * 12 readings per day)

-- Delete existing test readings first
DELETE FROM readings WHERE sensor_id IN (@tomato_moisture_id, @tomato_temp_id, @basil_moisture_id, @basil_humidity_id, @lettuce_moisture_id);

-- Insert readings for Tomato Moisture Sensor (values between 30-70%)
INSERT INTO readings (sensor_id, value, unit, temperature, humidity, created_at)
SELECT 
    @tomato_moisture_id,
    ROUND(30 + (RAND() * 40), 2),  -- Random value between 30-70%
    '%',
    NULL,
    NULL,
    DATE_SUB(NOW(), INTERVAL (12 * 7 - seq) HOUR)
FROM (
    SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83
) as seq_table;

-- Insert readings for Tomato Temperature Sensor (values between 18-28°C)
INSERT INTO readings (sensor_id, value, unit, temperature, humidity, created_at)
SELECT 
    @tomato_temp_id,
    ROUND(18 + (RAND() * 10), 2),  -- Random value between 18-28°C
    '°C',
    ROUND(18 + (RAND() * 10), 2),
    NULL,
    DATE_SUB(NOW(), INTERVAL (12 * 7 - seq) HOUR)
FROM (
    SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83
) as seq_table;

-- Insert readings for Basil Moisture Sensor (values between 40-80%)
INSERT INTO readings (sensor_id, value, unit, temperature, humidity, created_at)
SELECT 
    @basil_moisture_id,
    ROUND(40 + (RAND() * 40), 2),  -- Random value between 40-80%
    '%',
    NULL,
    NULL,
    DATE_SUB(NOW(), INTERVAL (12 * 7 - seq) HOUR)
FROM (
    SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83
) as seq_table;

-- Insert readings for Basil Humidity Sensor (values between 50-90%)
INSERT INTO readings (sensor_id, value, unit, temperature, humidity, created_at)
SELECT 
    @basil_humidity_id,
    ROUND(50 + (RAND() * 40), 2),  -- Random value between 50-90%
    '%',
    NULL,
    ROUND(50 + (RAND() * 40), 2),
    DATE_SUB(NOW(), INTERVAL (12 * 7 - seq) HOUR)
FROM (
    SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83
) as seq_table;

-- Insert readings for Lettuce Moisture Sensor (values between 35-75%)
INSERT INTO readings (sensor_id, value, unit, temperature, humidity, created_at)
SELECT 
    @lettuce_moisture_id,
    ROUND(35 + (RAND() * 40), 2),  -- Random value between 35-75%
    '%',
    NULL,
    NULL,
    DATE_SUB(NOW(), INTERVAL (12 * 7 - seq) HOUR)
FROM (
    SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83
) as seq_table;

-- Show summary
SELECT 'Test data seeded successfully!' as message;
SELECT COUNT(*) as plant_count FROM plants WHERE name IN ('Tomato Plant', 'Basil Plant', 'Lettuce Plant');
SELECT COUNT(*) as sensor_count FROM sensors WHERE name LIKE '%Tomato%' OR name LIKE '%Basil%' OR name LIKE '%Lettuce%';
SELECT COUNT(*) as reading_count FROM readings WHERE sensor_id IN (@tomato_moisture_id, @tomato_temp_id, @basil_moisture_id, @basil_humidity_id, @lettuce_moisture_id);

